travis:
  secure:
    BINSTAR_TOKEN: QSPc6sX7XODk/dPvvsEwuV8nnBxO5wxgYhvQFLy6Ibf6JILxVxI5q6LUFgo3vsOVKznacI2JRWyDus0xBqlH3zU4QbUcSBDhtd7/48f3ffgjwgteHe8jwb4frlCJX+R6L6v+Os0NN5CmMNq2B/AArXqjdOLqrEq2j0aSPEyGcd3+Lf9KFOx5RXytWl6umT4Qu5opMLrxhWJZ4Ywv6I5VXR4QzbgNMRFMXOXlEYUHlvIGYgr85a2HvzeCCxo/GpHmHMli9cPPGY2aVPIO0dp1616bSA/KtHc96BBXx9mkW8TA3830AnrOn1LVa1NjA9HTyG4P14V3k3JHncoAbpF+2nJM/9BEMVkV+6gu1GAADUpyS+fZG7oVwf9ykKi4Im3iJppAYsD072kgehfAlUBWFaVi2U0hTIZHFtqaQAWE87sogEhUMKvTayfQxQuadXmxB8vixbKVt9kThHU2WaDiOiSJrnsZsdMXOW2u1iASxR17YNroinODgLhHECU9EgYAPqfzW+AqKB0YaaRI7U/nB83uMTvOlj+2xXDm8O2E3X1a0/zd2MZfjNSgkb05RfI6pw+A16uJqPH9z2P1j+s6PnPksUM/Kpmmw9kWUReIjC51/lBiZSOcVsuNrJACd7UAeK1pzNeIFvSkus665swaMdOVE3tEgpG/LW/bnyuIhOk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
